// See https://aka.ms/new-console-template for more information


/*
 * Company sales are 5300000
 * West Coast sales unit generates 43% of the sales for the company.
 * What is the amount that West Coast sales unit generates?
 */

double generatedSalesAmountByWestCoastUnit;

generatedSalesAmountByWestCoastUnit = 5300000 * .43;

Console.WriteLine($"Amount generated by West Coast Sales was: {generatedSalesAmountByWestCoastUnit}");
